spring:
  application:
    name: BoardAdmin
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: ${db_url}
    username: ${db_username}
    password: ${db_password}
  jpa:
    show-sql: true

  thymeleaf:
    prefix: classpath:/templates/view/
    suffix: .html

mybatis:
  type-aliases-package: com.example.board.model
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    jdbc:
      sqlonly: trace
      audit: off
      resultset: off
      connection: off